### ISSUE TITLE
[BUG] (dev) CircleCI config is not building develop or release branches

### ISSUE THREAD

**Issue by zetlen** [magento-research/pwa-studio#1042]
CircleCI configuration is currently set up to only build pull requests. It makes an exception for the default branch: that branch is `develop`. But we also need it to build master and release branches.

**To Reproduce**
1. Merge to a release branch.
2. Visit the [CircleCI dashboard for this repository.](https://circleci.com/gh/magento-research/pwa-studio}

**Expected behavior**
The release branch build process has kicked off (and succeeds).

**Screenshots**

The offending configuration in `.circleci/config.yml`:

```yaml
version: 2
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - master:
          filters:
            branches:
              only: master
```

The build doesn't run:

![image](https://user-images.githubusercontent.com/1643758/54704830-833b4800-4b09-11e9-8e8f-1504f0206e8f.png)

![image](https://user-images.githubusercontent.com/1643758/54704847-8c2c1980-4b09-11e9-81f6-429d9e7515be.png)

**Additional context**
This must be fixed for the 2.1 release process in #1026 .

**Possible solutions**
Modify `.circleci/config.yml` workflow config to build master and release branches.
