### ISSUE TITLE
Upward-js unable to serve images

### ISSUE THREAD

**Issue by pcvonz** [magento-research/pwa-studio#408]
## This issue is for the following packages:

[ ] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[X] `upward-js`
[ ] `upward-spec`

## This issue is a:

[X] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

Quote from issue #372

I'm trying to add the icon images in the same manner that the `favicon` is being served in the upward yaml. [in Venia]

```yml
# Upward yaml
...
    - matches: request.url.pathname
      pattern: '^/homescreen144.png'
      use: homescreen
...
homescreen:
  inline:
    status: 200
    headers:
      inline:
        content-type:
          inline: image/png
    body:
      file:
        inline: ./media/icons/homescreen144.png
      encoding: binary
```

The response headers:

```
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: image/png; charset=utf-8
Content-Length: 16561
ETag: W/"40b1-cBSYqciI/b0yfdYRj1qYfNGogTU"
Date: Mon, 22 Oct 2018 23:59:42 GMT
Connection: keep-alive

```

Request headers:

```
GET /homescreen144.png HTTP/1.1
Host: magento-venia-concept-eejeb.local.pwadev:9563
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/69.0.3497.81 Chrome/69.0.3497.81 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: PHPSESSID=5k8b5vq2vo11ta7mavci6setq2
```

Navigating directly to the URL results in this page: 

![screen shot 2018-10-22 at 17 06 22](https://user-images.githubusercontent.com/6378569/47326283-e093a180-d61c-11e8-8886-1e0c90ed7337.png)

My guess is that it has something to do with this line:

```
Content-Type: image/png; charset=utf-8
```
But I'm not sure.

@zetlen have any ideas?

## Expected result:

To properly display an image on the client's device. 

## Possible solutions:

I'm no express expert, but changing the `.send(response.body)` line to `.send(new Buffer(response.body, 'binary'));` fixes the issue.
