### ISSUE TITLE
[Styles]: Close button displayed incorrect for cart

### ISSUE THREAD

**Issue by vitalics** [magento-research/pwa-studio#565]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[X] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description
close cart button displayed incorrect as you can see on screenshot below
![image](https://user-images.githubusercontent.com/8816260/49226253-27806e00-f3f7-11e8-8870-9c567a296a97.png)

## Expected result:
![image](https://user-images.githubusercontent.com/8816260/49226331-4bdc4a80-f3f7-11e8-8b76-82cf6833ad8c.png)

## Possible solutions:
in class `miniCart-header` fix styles:
``` css
.miniCart-header{
    grid-template-columns: 0.9fr; /* was 1fr */
    justify-content: end; /* remove this style rule */
}
```
